### ISSUE TITLE
Difference between "Custom-Krunker-Client"

### ISSUE THREAD

**Issue by NLDev** [Mixaz017/idkr#7]
First of all: Thank you for your amazing work :) 

Just wanted to ask what the difference between this client here and the [Custom-Krunker-Client](https://github.com/Mixaz017/Custom-Krunker-Client) was. I've run into a few issues with the Custom-Krunker-Client and saw it hasn't been updated in a while. Is this the new version?

**Comment by Mixaz017** [comment]
I stopped developing Custom to start developing this client, but its not meant to be a new version of Custom. Its concept is different, the code is written from scratch.

**Comment by NLDev** [comment]
Hi! Thanks for your answer :) 

Quick follow up question: 
Is it stable yet? Problem is, I recently started getting a lot of FPS issues on the official client from the Krunker website. I used to get about 200 FPS and now it's somehow down to 12-14 FPS (I'm on Linux). I didn't really debug but it seems like the client doesn't use hardware acceleration anymore. That's why I started to search for an alternative and your custom client fixed that issue for me. Cant play it in browser either since I only get like 60 FPS. Problem is, the custom client randomly freezes after a game ends or after I got killed. To "un-freeze" I have to press F11 to toggle full-screen. Once I enter or exit full-screen it unfreezes. 

So would you recommend sticking to the custom client or using this one here?

**Comment by Mixaz017** [comment]
I dont recommend sticking to Custom as it uses older version of the official client as its base code, and its no longer actively maintained. idkr has an option that lets you change the graphics backend so you can mess around with that option to find the best backend (in terms of performance or stability). I believe idkr also has freeze problems because some users reported it but I dont get freeze problems so Im not sure if its still a thing. Im not really sure but you can always try the client and quit using it if you want.

**Comment by NLDev** [comment]
Alright! Awesome :) 
Thanks!

**Comment by NLDev** [comment]
Just a quick follow up: 
Everything works like a charm. No FPS issues, no freezes, no lag. 
Thank you so much for this! :)
